### ISSUE TITLE
api.update() causes OSError: [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad-library-manager#32]
On Linux, `/tmp` might be a separate filesystem, e.g. of type `tmpfs`
```
$ df /tmp/
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs           16286060 92280  16193780   1% /tmp

```
This causes an error with `os.rename()` as rename is not allowed across different filesystems.

```
$ python3
Python 3.12.4 (main, Jul 15 2024, 12:17:32) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import olman_client.api as o
>>> o.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tp/projects/o/olman.git/.venv/lib/python3.12/site-packages/olman_client/api.py", line 10, in update
    return remote_index.update(force=force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/projects/o/olman.git/.venv/lib/python3.12/site-packages/olman_client/internal/remote_index.py", line 58, in update
    _download()
  File "/home/tp/projects/o/olman.git/.venv/lib/python3.12/site-packages/olman_client/internal/remote_index.py", line 27, in _download
    downloadFile(
  File "/home/tp/projects/o/olman.git/.venv/lib/python3.12/site-packages/olman_vcs_utils/vcs_utils.py", line 91, in downloadFile
    dst = tmp_path.rename(dst)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1365, in rename
    os.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpcz4wvnae' -> '/home/tp/.local/share/olman/remote_index.json'
>>> 
```

**Comment by t-paul** [comment]
With `dst` being the `Path()` of the target file, something like
```
tf = NamedTemporaryFile(dir = dst.parent, prefix=dst.stem + ".", suffix=dst.suffix)
tmp_path, response = urlretrieve(url=url, filename=tf.name)
```
should be safe as it will always store the temp file in the same folder.
